package com.yoyuzh.admin;

public enum AdminAuditAction {
    UPDATE_REGISTRATION_INVITE_CODE,
    ROTATE_REGISTRATION_INVITE_CODE,
    UPDATE_OFFLINE_TRANSFER_STORAGE_LIMIT,
    UPDATE_USER_ROLE,
    UPDATE_USER_BANNED,
    UPDATE_USER_PASSWORD,
    RESET_USER_PASSWORD,
    UPDATE_USER_STORAGE_QUOTA,
    UPDATE_USER_MAX_UPLOAD_SIZE,
    DELETE_SHARE,
    DELETE_FILE,
    CREATE_STORAGE_POLICY,
    UPDATE_STORAGE_POLICY,
    UPDATE_STORAGE_POLICY_STATUS,
    CREATE_STORAGE_POLICY_MIGRATION_TASK,
    UPDATE_SYSTEM_SETTINGS
}
