package com.yoyuzh.ops.admin.internal.application;

public enum AdminAuditAction {
    USER_ROLE_UPDATED,
    USER_STATUS_UPDATED,
    USER_PASSWORD_UPDATED,
    USER_PASSWORD_RESET,
    USER_STORAGE_QUOTA_UPDATED,
    USER_MAX_UPLOAD_SIZE_UPDATED,
    FILE_DELETED,
    SHARE_DELETED,
    SETTINGS_UPDATED,
    INVITE_CODE_UPDATED,
    INVITE_CODE_ROTATED,
    OFFLINE_TRANSFER_LIMIT_UPDATED,
    STORAGE_POLICY_CREATED,
    STORAGE_POLICY_UPDATED,
    STORAGE_POLICY_STATUS_UPDATED,
    STORAGE_POLICY_MIGRATION_REQUESTED,
    CONFIG_VALUE_UPDATED,
    CONFIG_VALUE_ROLLED_BACK
}
